<template>
    <div>
        <h1>来校路线</h1>
        <img src="../../assets/share.png" alt="">
        <img src="../../assets/button.jpg" alt="">
    </div>
</template>

<script type="text/ecmascript-6">
    export default {
        name: 'way',
        data(){
            return {}
        }
    }
</script>

<style scoped>
    h1 {
        font-size: 2.4em;
        background-color: #292929;
        text-align: center;
        padding: 20px;
        margin: 0;
        color: #fff;
    }
</style>