<template>
    <div>
        <div class="main">
            <div class="fast">
                <ul>
                    <section id="custom_html-11" class="widget_text widget widget_custom_html">
                        <div class="textwidget custom-html-widget">
                            <li style="border: none;">
                                <a href="" target="_blank">
                                    <img src="../../../assets/fast_ico01.png">
                                    <span>每周(8-20)企业上门招聘<br>高薪就这么简单的事！</span>
                                </a>
                            </li>
                            <li>
                                <a target="_blank">
                                    <img src="../../../assets/fast_ico02.png">
                                    <span>7月申请免费名额<br>名额有限，先到先得</span>
                                </a>
                            </li>
                            <li><a href="http://bbs.bjsxt.com/thread-2-1-1.html" target="_blank">
                                <img src="../../../assets/fast_ico03.png">
                                <span>一张帖60个问题<br>全面了解尚学堂</span>
                            </a>
                            </li>
                            <li>
                                <a href="http://720yun.com/t/19920upujci?pano_id=1457034" target="_blank">
                                    <img src="../../../assets/fast_ico04.png">
                                    <span>只需2分钟<br>全面了解尚学堂</span>
                                </a>
                            </li>
                        </div>
                    </section>
                </ul>
            </div>
        </div>
    </div>
</template>

<script type="text/ecmascript-6">
    export default {
        name: 'java',
        data(){
            return {}
        }
    }
</script>

<style scoped>
    .main {
        width: 1300px;
        margin: 30px 50px;
        position: relative;
    }

    .fast {
        background: #fff;
        border: #ccc solid 1px;
        overflow: hidden;
    }

    article, aside, footer, header, hgroup, main, nav, section {
        display: block;
    }

    .fast ul li span {
        float: left;
        font-size: 16px;
        line-height: 26px;
        padding: 25px 0 0 0;
        color: #0f0f0f;
    }

    .fast ul li {
        width: 298px;
        float: left;
        border-left: #ccc solid 1px;
        overflow: hidden;
    }

    .fast ul li img {
        float: left;
        width: 63px;
        height: 63px;
        margin: 20px 15px 20px 25px;
    }

    img {
        border: none;
    }


</style>